---
engine_version: 0.4.36
file_version: 2025-06-07 12:58:04.244667000 -03:00
resources:
- name: backup_log
  preferences:
    scopes:
    - visible: false
      name: not_success
    - visible: false
      name: not_failure
    visible: false
  updated_at: 2025-06-05 12:45:54.240004000 +00:00
- name: backup_routine
  preferences:
    scopes:
    - visible: false
      name: not_daily
    - visible: false
      name: not_hourly
    - visible: false
      name: not_weekly
    columns:
    - default_value: "[]"
      description: Comma separated
      name: tables_to_exclude
    - default_value: "[]"
      description: Comma separated
      name: tables_to_exclude_data
  updated_at: 2025-06-05 14:03:49.090657000 +00:00
- name: backup_run
  preferences:
    actions:
    - name: delete_file_from_storage
      display_name: Delete file from Storage
      action_type: method
      preferences:
        method_name: delete_remote_file!
    scopes:
    - visible: false
      name: not_failed
    - visible: false
      name: not_running
    - visible: false
      name: not_completed
  updated_at: 2025-06-07 12:58:04.244667000 +00:00
- name: destination
  preferences:
    scopes:
    - visible: false
      name: not_s3
    - visible: false
      name: not_google_drive
  updated_at: 2025-06-05 12:30:56.618353000 +00:00
- name: solid_queue/blocked_execution
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:13.480425000 +00:00
- name: solid_queue/claimed_execution
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:14.694352000 +00:00
- name: solid_queue/failed_execution
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:15.171853000 +00:00
- name: solid_queue/job
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:24.430922000 +00:00
- name: solid_queue/pause
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:25.191725000 +00:00
- name: solid_queue/process
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:30.731994000 +00:00
- name: solid_queue/ready_execution
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:31.928974000 +00:00
- name: solid_queue/recurring_execution
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:32.835668000 +00:00
- name: solid_queue/recurring_task
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:33.864010000 +00:00
- name: solid_queue/scheduled_execution
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:34.907225000 +00:00
- name: solid_queue/semaphore
  preferences:
    visible: false
  updated_at: 2025-06-05 01:41:36.141097000 +00:00
configs:
- key: header.links
  value:
  - name: Reports
    link_type: reports
  - name: Forms
    link_type: forms
  updated_at: 2025-06-05 12:31:50.527958000 +00:00
- key: resources.backup_routine.columns.order
  value:
  - id
  - database_connection_id
  - destination_id
  - name
  - frequency
  - run_at
  - tables_to_exclude
  - tables_to_exclude_data
  - no_owner
  - no_privileges
  - updated_at
  - created_at
  updated_at: 2025-06-05 14:17:01.715615000 +00:00
- key: resources.order
  value:
  - destination
  - database_connection
  - backup_routine
  - backup_log
  - solid_queue/blocked_execution
  - solid_queue/claimed_execution
  - solid_queue/failed_execution
  - solid_queue/job
  - solid_queue/pause
  - solid_queue/process
  - solid_queue/ready_execution
  - solid_queue/recurring_execution
  - solid_queue/recurring_task
  - solid_queue/scheduled_execution
  - solid_queue/semaphore
  updated_at: 2025-06-05 12:32:08.056332000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2025-06-05 01:17:46.548138000 +00:00
