production:
  prune_backups:
    class: PruneBackupsJob
    queue: backups
    schedule: at 4am every day

development:
  prune_backups:
    class: PruneBackupsJob
    queue: backups
    schedule: at 4am every day
