default: &default
  scheduler_keepalive:
    # Stub task to keep the scheduler alive
    command: "Rails.logger.info('[SQ] scheduler tick: ' + Time.current.to_s)"
    schedule: "every 10 minutes"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
