# == Schema Information
#
# Table name: database_connections
# Database name: primary
#
#  id                 :integer          not null, primary key
#  connection_mode    :string           default("direct"), not null
#  database_name      :string
#  host               :string
#  name               :string
#  password           :string
#  port               :integer
#  ssh_host           :string
#  ssh_known_host_key :text
#  ssh_port           :integer          default(22)
#  ssh_private_key    :text
#  ssh_public_key     :text
#  ssh_user           :string
#  sslmode            :string
#  username           :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  workspace_id       :integer          not null
#
# Indexes
#
#  index_database_connections_on_workspace_id  (workspace_id)
#
# Foreign Keys
#
#  workspace_id  (workspace_id => workspaces.id)
#
class DatabaseConnection < ApplicationRecord
  belongs_to :workspace
  has_many :backup_routines, dependent: :destroy

  encrypts :password
  encrypts :ssh_private_key

  validates :name, :host, :port, :username, :password, :database_name, :sslmode, presence: true
  validates :port, numericality: { only_integer: true, in: 1..65_535 }
  validates :ssh_host, :ssh_user, presence: true, if: :ssh_tunnel?
  validates :ssh_port, numericality: { only_integer: true, in: 1..65_535 }, if: :ssh_tunnel?

  enum :connection_mode, { direct: "direct", ssh_tunnel: "ssh_tunnel" }, default: :direct

  enum :sslmode, {
    disable: "disable",
    allow: "allow",
    prefer: "prefer",
    require: "require",
    verify_ca: "verify-ca",
    verify_full: "verify-full"
  }, default: :prefer

  before_validation :generate_ssh_keypair, if: -> { ssh_tunnel? && ssh_private_key.blank? }

  # Everything pg_dump/psql need except the password, which is passed through
  # the spawned process environment only (never argv, never a URL).
  def pg_env
    {
      "PGHOST" => host,
      "PGPORT" => port.to_s,
      "PGUSER" => username,
      "PGPASSWORD" => password,
      "PGDATABASE" => database_name,
      "PGSSLMODE" => sslmode_before_type_cast
    }
  end

  # Yields the environment pg_dump/psql should run with. For tunneled
  # connections the block runs while the SSH tunnel is up, with host/port
  # rewritten to its local end; `host` is then resolved from the SSH server's
  # point of view (usually localhost).
  def with_pg_env(&block)
    return yield(pg_env) if direct?

    Backups::SshTunnel.open(self) do |local_port|
      yield pg_env.merge("PGHOST" => "127.0.0.1", "PGPORT" => local_port.to_s)
    end
  end

  # Called after a first successful SSH connection pins the server's host key.
  def pin_ssh_host_key!(key_blob)
    update_column(:ssh_known_host_key, key_blob)
  end

  private

  # The keypair is generated by the app: the public half is shown in the UI to
  # be added to the server's authorized_keys, the private half is encrypted at
  # rest and never leaves the app. RSA-4096 keeps this stdlib-only (net-ssh
  # signs with rsa-sha2, accepted by modern sshd).
  def generate_ssh_keypair
    key = OpenSSL::PKey::RSA.new(4096)
    self.ssh_private_key = key.to_pem
    self.ssh_public_key = "ssh-rsa #{[ openssh_blob(key) ].pack("m0")} vitapg"
  end

  def openssh_blob(key)
    [ "ssh-rsa", key.e.to_s(2), key.n.to_s(2) ].map { |part|
      prefix = part.start_with?("ssh-") ? "" : (part.getbyte(0) >= 0x80 ? "\x00" : "")
      [ (part.bytesize + prefix.bytesize), prefix, part ].pack("Na*a*")
    }.join
  end
end
